/*
 * Pull the design layer in from its source repo and stamp a manifest.
 *
 * lalaf02/sievan-design remains where the design is authored and reviewed. It is
 * vendored here rather than installed because a private git dependency cannot be
 * fetched inside a Vercel build container without a token, and every mechanism
 * for supplying one failed in a way that was invisible locally.
 *
 * Run this after changing the design repo, then commit the result.
 *   npm run design:sync
 */
import { cpSync, rmSync, mkdirSync, existsSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hashTree } from './design-hash.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, '..', 'sievan-design');
const DEST = join(ROOT, 'design');
const COPY = ['tokens.css', 'primitives.css', 'index.ts', 'theme.ts', 'primitives', 'DESIGN.md', 'scripts'];

if (!existsSync(SRC)) {
  console.error(`  sync-design: ${SRC} not found.`);
  console.error('  Clone it beside this repo: git clone git@github.com:lalaf02/sievan-design.git');
  process.exit(1);
}

rmSync(DEST, { recursive: true, force: true });
mkdirSync(DEST, { recursive: true });
for (const entry of COPY) {
  const from = join(SRC, entry);
  if (existsSync(from)) cpSync(from, join(DEST, entry), { recursive: true });
}

let commit = 'unknown';
let sourceDirty = false;
try {
  commit = execFileSync('git', ['-C', SRC, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
  sourceDirty = Boolean(execFileSync('git', ['-C', SRC, 'status', '--porcelain'], { encoding: 'utf8' }).trim());
} catch { /* a source checkout without git history still vendors fine */ }

writeFileSync(join(DEST, 'README.md'), `# Vendored design layer — do not edit here

Authored in [lalaf02/sievan-design](https://github.com/lalaf02/sievan-design);
this directory is a copy, and \`scripts/check-design.mjs\` fails the build if it
is edited in place. Change it there, then run \`npm run design:sync\` and commit.

Vendored from commit \`${commit}\`${sourceDirty ? ' with local source changes (not yet committed)' : ''}.

The contract these files implement is in [DESIGN.md](./DESIGN.md).
`);

writeFileSync(join(DEST, 'MANIFEST.json'), `${JSON.stringify({
  source: 'https://github.com/lalaf02/sievan-design',
  commit,
  sourceDirty,
  hash: hashTree(DEST),
  note: 'Generated by scripts/sync-design.mjs. Do not edit design/ directly.',
}, null, 2)}\n`);

console.log(`  sync-design: vendored from ${commit.slice(0, 8)}`);
